### ISSUE TITLE
What are the requirements for the gltf and bin files in blended-skinned-mesh

### ISSUE THREAD

**Issue by ssooffiiaannee** [KDAB/qt3d-examples#6]
I'm trying to use my own customised gltf and .bin on the blended-skinned-mesh program, I removed the controllerwidget, the animation code lines too (I commented them), just to see the imported object, I tried the robot.gltf, it works well, it show a static rabot with its texture, (no controllerwidget and no animation), 
![image](https://user-images.githubusercontent.com/37119086/89032166-5d949480-d334-11ea-94c8-e905b863310f.png)

but when I use the same robot.gltf file, but I export it my way using blender, I get nothing, only the background appears
![image](https://user-images.githubusercontent.com/37119086/89032117-3e960280-d334-11ea-9a47-f54b85c98d08.png)

along with these error messages:
![image](https://user-images.githubusercontent.com/37119086/89093267-13a1c200-d3b9-11ea-8e9c-f79f4954c42d.png)

so does the blended-skinned-animation project depend on blender version or anything else?

**Comment by lemirep** [comment]
When using that approach I believe you have to export the animation / skeleton information using the scripts in https://code.qt.io/cgit/qt/qt3d.git/tree/tools/utils/exporters/blender. You'll have to copy them in your blender script directly and enable them in the Blender Addon settings menu first

**Comment by ssooffiiaannee** [comment]
But I want to export them into gltf and bin format, these scripts export into json format.

**Comment by lemirep** [comment]
Could be wrong indeed, skeleton seems to be coming from the gltf itself.

From what I recall that example was made with Blender 2.79 and exporter used at the time was https://github.com/Kupoman/blendergltf

The fact you are not seeing anything could be due to a lot of things, some that come to mind are:
- skeleton not loaded or not exported into gltf
- gltf object not within the camera field of view
- world dimension of model too large or too small
- missing options when exported (modifiers not applied, no animation exported, no skeleton exported, ...)

You could try checking you have a skin/skeleton in the gltf file that gets exported from blender similar to https://github.com/KDAB/qt3d-examples/blob/master/resources/assets/gltf/2.0/Robot/robot-run.gltf

**Comment by ssooffiiaannee** [comment]
I compared the files, they are different but I can find the material, skins, armature in both of them, I can't tell the source of the problem, Is it possible to provide the .blend where the robot.gltf and robot.bin files came from? 
Am I the only person who is trying this out with other blender skinned meshes? or is there an easier way to do it that I ignore?

**Comment by lemirep** [comment]
The GLTF importer that comes bundled with Qt3D is best support only, Qt will glady accept contributions though. If you want a fully compliant gltf import to use with Qt3D (including animations and skinned meshes), I would recommend using Kuesa which is tested against the latest blender versions.
